### ISSUE TITLE
Null ref exception collecting coverage after upgrading from 0.5.0 to 0.6.0

### ISSUE THREAD

**Issue by DanTup** [dart-lang/coverage#50]
After upgrading from 0.5.0 to 0.6.0, I get the following error when starting collect_coverage and firing up Dartium (the error doesn't occur until Dartium loads).

```
Unhandled exception:
Uncaught Error: The null object does not have a method 'map'.

NoSuchMethodError: method not found: 'map'
Receiver: null
Arguments: [Closure: (dynamic) => dynamic]
Stack Trace:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      VM.VM.fromJson (package:coverage/src/devtools.dart:109)
#2      VMService.getVM.<anonymous closure> (package:coverage/src/devtools.dart:21)
#3      _RootZone.runUnary (dart:async/zone.dart:1155)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:567)
#6      _Future._completeWithValue (dart:async/future_impl.dart:358)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
```

I'm starting it like this:

```powershell
$testInstance = "http://dart-tests/"
$dartiumPath = "C:\Work\Utilities\dartium\chrome.exe"
$dartiumProfilePath = "C:\Work\Utilities\dartium-profile"
$timeoutSeconds = 10
$debuggerPort = 8091
$dartSDK = "%DART_SDK%"

# Start listening for coverage
Write-Host "Starting collect_coverage..."
$proc = Start-Process pub -ArgumentList ("global", "run", "coverage:collect_coverage", "--port=$debuggerPort", "-o coverage/coverage.json", "--connect-timeout=$timeoutSeconds") -PassThru

# Start Dartium and run the tests
Write-Host "Starting Dartium to run tests..."
$dartium = Start-Process $dartiumPath -ArgumentList ("--remote-debugging-port=$debuggerPort", "--user-data-dir=$dartiumProfilePath", "--disable-web-security", $testInstance) -PassThru
```

I'm on Windows 8.1 Enterprise, Dart VM version: 1.8.5 (Tue Jan 13 13:38:34 2015) on "windows_x64".
Dartium version is 38.0.2125.0 (Developer Build 292384).

**Comment by cbracken** [comment]
Thanks - looking!

**Comment by cbracken** [comment]
There were some very significant changes to the VM observatory protocol in versions 1.9.0, 1.10.0 and again in 1.11.0.  This should be corrected by recent patches to support newer protocol versions. I've tested on Linux and OS X, but don't have a Windows machine to test against. If you're still seeing the issue, let me know and I'll see what I can do.
